// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Dwapi.Bot.Infrastructure.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Configs.MatchConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MatchConfigs");
                });

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Indices.SubjectIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MpiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientID")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientPk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Serial")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dmFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("dmLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("dmMiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("dmPKValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("dmPKValueDoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxMiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxPKValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxPKValueDoB")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxdmPKValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("sxdmPKValueDoB")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubjectIndices");
                });

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Indices.SubjectIndexScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OtherSubjectIndexId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScanLevelCode")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectIndexId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectIndexId");

                    b.ToTable("SubjectIndexScores");
                });

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Indices.SubjectIndexStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusInfo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectIndexId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectIndexId");

                    b.ToTable("SubjectIndexStages");
                });

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Indices.SubjectIndexScore", b =>
                {
                    b.HasOne("Dwapi.Bot.Core.Domain.Indices.SubjectIndex", null)
                        .WithMany("IndexScores")
                        .HasForeignKey("SubjectIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dwapi.Bot.Core.Domain.Indices.SubjectIndexStage", b =>
                {
                    b.HasOne("Dwapi.Bot.Core.Domain.Indices.SubjectIndex", null)
                        .WithMany("IndexStages")
                        .HasForeignKey("SubjectIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
